planner_node:
  ros__parameters:
    map_topic: "/map"
    robot_pose_topic: "/pf/pose/odom"
    waypoints_topic: "/interface/waypoints"
    path_topic: "/planning/path"

    occupied_threshold: 50
    unknown_is_occupied: true
    inflation_radius_m: 0.3

    allow_diagonal: true
    astar_timeout_ms: 300

    resample_ds: 0.10
    min_path_points: 2

    smoothing_enable: true
    smoothing_alpha: 0.1
    smoothing_beta: 0.3
    smoothing_iterations: 50
